# SPDX-License-Identifier: MIT
# Copyright: 2024-2026 Paillat-dev
name: Quality Checks

on:
  workflow_call:

jobs:
  check-license-header:
    name: License Header Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Licensor
        uses: nicebots-xyz/licensor/.github/actions/setup-licensor@20ff71ae4c0ca9874893c11c7c2cbdb9d22e179e # v0.1.0
        with:
          version: v0.1.0
      - name: Check Header Compliance
        run: licensor check * --ignore ".*"

  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [format, lint, basedpyright]
        include:
          - check: format
            name: "Format Check"
            command: "uv run ruff format --check ."
          - check: lint
            name: "Lint Check"
            command: "uv run ruff check ."
          - check: basedpyright
            name: "Type Check"
            command: "uv run basedpyright ."

    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync

      - name: ${{ matrix.name }}
        run: ${{ matrix.command }}